id: I57D414B1
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T13:09:51.659167'
last_modified: '2022-06-19T13:09:51.659183'
parser: null
source_metadata:
  title: Hagiography of Ngor chen Kun dga' bzang po (1382-1456), no. II; Lamdre Lobshe,
    vol. ka, title no. 22, volume two from the chronological biographies of the Lamdre
    lineage masters
  author: སངས་རྒྱས་ཕུན་ཚོགས།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-19);
    converted from external file, unrevised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/375
  bases:
    14bf:
      title: Hagiography of Ngor chen Kun dga' bzang po (1382-1456), no. II; Lamdre
        Lobshe, vol. ka, title no. 22, volume two from the chronological biographies
        of the Lamdre lineage masters
      order: 1
      base_file: 14bf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
